name: hello-world

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest 

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v7

      - name: Installer Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 24.18.0
          cache: npm

      - name: Installer les dépendances
        run: npm hello-world

      - name: Lancer les tests
        run: npm test

      - name: Écrire le résumé
        run: |
          echo "## Résultat " >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Statut du job :** ${{ job.status }}" >> $GITHUB_STEP_SUMMARY
          echo "**Commit :** ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
          echo "**Ref :** ${{ github.ref }}" >> $GITHUB_STEP_SUMMARY
